# Generated by Django 5.0.7 on 2024-08-03 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('blogs_app', 'Category')
    initial_categories = ['Mental Health', 'Heart Disease', 'Covid19', 'Immunization']
    for category_name in initial_categories:
        Category.objects.create(name=category_name)
        
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('is_draft', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs_app.category')),
            ],
        ),
        migrations.RunPython(create_initial_categories),
    ]
